### 월별 리포트
GET localhost:8080/monthly-electricity/2024-04-30T00:00:00

### 이상치 알람 보내기
POST localhost:8080/notify
X-Accel-Buffering: no
Content-Type: application/json

{
  "deveui": "24E124445D189958",
  "sensorName": "light",
  "place": "class_a",
  "type": "ac",
  "time": 17782937,
  "outlier_value": 12212,
  "organizationId": 1
}

###
GET localhost:8090/outlier

###
GET localhost:8080/daily/electricity/current-month
Cookie: iotaot=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiaWF0IjoxNzE2ODU0ODg1LCJleHAiOjE3MTY4NTg0ODV9.nqh2tGlbFS6OGIj3amQ2NtUS79Awaf5rYs52lwQ13Ew


###
GET localhost:8090/users
X-USER-ID: asdf

### anjrk
GET localhost:8090/daily/electricities/total?localDateTime=2024-05-28T00:00:00&organizationId=1

### 데일리 리포트 시간 별
GET localhost:8080/daily-report/-1
Cookie: iotaot=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmIiwiaWF0IjoxNzE2ODk1MTg0LCJleHAiOjE3MTY4OTg3ODR9.fRHD4kkkv3m2Zb0Alz9eNFffx616o1P-RpgAHGNrY_k
