server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${discovery.id}:${discovery.password}@${discovery.ip}:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: front-service
  thymeleaf:
    cache: false
  jackson:
    default-property-inclusion: non_null

  mvc:
    hiddenmethod:
      filter:
        enabled: true